### ISSUE TITLE
LittleBlueTooth#startListen behavior

### ISSUE THREAD

**Issue by NeverwinterMoon** [DrAma999/LittleBlueTooth#22]
First of all, great work on the library. I've just started with it and it's looking great!

I have a question though. When using `LittleBlueTooth#startListen`, I don't receive an initial value. Is this by design?

For example:
`littleBT.read(from: Self.BATTERY_CHARACTERISTIC)` will publish a value as soon as I subscribe
but
`littleBT.startListen(from: Self.BATTERY_CHARACTERISTIC)` will not publish anything as soon I subscribe

**Comment by DrAma999** [comment]
Hello sorry for replying so late, but Github doesn't notify me anymore.. don't know why.
I don't think is something about the library, but more bluetooth related.
When you read from a characteristic you are basically waiting for the pipeline to stop until the device reply with a value or an error.
When you subscribe to a characteristic it can depend on the the logic of the bluetooth device:

- Some devices continuously to send you the value even if it has not changed, this is battery consuming.
- Some devices continuously to send you the value at specific interval of time and when it has changed, this is less battery consuming.
- Some devices send value only if a value has changed  this is the more saving way.
- Also some device send you an initial value once you subscribe, I think that I saw an option on the Arduino side of my Arduino Nano

Depending on how is implemented the firmware of the device you can have on of these three behaviour(and probably more).

Best,
Andrea

**Comment by DrAma999** [comment]
Closing as stale
