### ISSUE TITLE
IOS-CoreBluetooth-Mock dependency breaks SwiftUI previews in Xcode 12.5

### ISSUE THREAD

**Issue by NeverwinterMoon** [DrAma999/LittleBlueTooth#25]
There is a fix for that but it hasn't been released: https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/issues/37

Otherwise, SwifUI previews don't work now because of this in Xcode 12.5. Probably, tests, too.

**Comment by DrAma999** [comment]
Hello @NeverwinterMoon ,
I've updated the dependency and tests are completing successfully (Xcode 12.5).
I only have a warning mentioning about the version mismatch but it doesn't seem to be blocking.
Not sure about this issue with swiftUI Preview, in my experience swiftUI preview are a really pain... and the failure could be for a plenty of reasons.
I've also created a super simple project just with the swiftUI boilerplate code, the LittleBluetooth dependency and imported the library as well,  it seems to create correctly the preview.
Can you be more specific?

**Comment by DrAma999** [comment]
Closing as stale
