### ISSUE TITLE
List of services

### ISSUE THREAD

**Issue by 666bsw** [DrAma999/LittleBlueTooth#35]
Hello!
how can i scan the list of available services?

Thank you

**Comment by 666bsw** [comment]
Hello, Andrea!
I want to scan the device and find out the list of services that are on the device.
services are not known in advance.
device scanner.

Thank you,
Sergey

**Comment by DrAma999** [comment]
Ok, understood.
Unfortunately at the moment is not possible, you always need to know in advance services and characteristics that are discovered (confirmed) lazy during read/write/notify requests.
It shouldn't be difficult to ad that feature but I can't make any promise about when I will be available to do it.
In the meantime any pull-request is well accepted if you want to try to implement it by yourself. `getService` method of `Peripheral` is a good starting point.
Best,
Andrea

**Comment by 666bsw** [comment]
thanks!
I already realized that this is impossible.
the framework is very user-friendly, respect
this is the only thing that I lacked

Thank you,
Sergey
