### ISSUE TITLE
Discovering services

### ISSUE THREAD

**Issue by vhscott** [DrAma999/LittleBlueTooth#39]
Not really an issue; but more on the usage. 

How do you use this to discover services and characteristics after finding the peripheral with discovery?

Thanks!

**Comment by DrAma999** [comment]
Hello,
For the moment this functionality is used only internally, basically you have to know in advance which services and characteristic you want to communicate with see this [issue](https://github.com/DrAma999/LittleBlueTooth/issues/35).
I don’t know when I will have time to do that but feel free to create a pull request.
Best, 
Andrea
