### ISSUE TITLE
Preservation and restauration example app

### ISSUE THREAD

**Issue by jaksatomovic** [DrAma999/LittleBlueTooth#42]
I neee more details :)

**Comment by DrAma999** [comment]
I need more details too :)
What have you tried tried so far?
What is the thing that is not clear in using it or what are the issues that you've encountered?
Did you read the suggested documents linked in the read me? I'm referring to [this](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html),  [this](https://developer.apple.com/library/archive/qa/qa1962/_index.html)  and [this](https://thexcodewhisperer.medium.com/core-bluetooh-state-preservation-and-restoration-f107031b32fa) .

**Comment by jaksatomovic** [comment]
Hi, thanks for the reply. Ill look into that.
One more question before I close this issue.
I'm trying to scan for peripherals and list all discoveries in action sheet allowing user to select the one he wants to connect to. Could you give an example code for that using StartLittleBlueTooth

**Comment by jaksatomovic** [comment]
I would appriciate any feedback soon. I can not manage to get it working using StartLittleBlueTooth and scan()

**Comment by DrAma999** [comment]
In the documentation there is a link to a simple sample app that you can use to scan and connect to peripheral.
As before I would suggest you to read the documentation, read the snippets provided.
If something doesn't work as you expected always provide an MVP that can replicate the issue.
Best
